name: AutoCI Pipeline

on:
  push:
    branches:
      - main
      - master

env:
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/autoci-app
  CONTAINER_NAME: autoci-app
  NEW_CONTAINER: autoci-app-new

jobs:
  build-test-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set version
        run: echo "VERSION=1775646302" >> $GITHUB_ENV

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build new version
        run: |
          docker build --no-cache -t $IMAGE_NAME:$VERSION .
          docker tag $IMAGE_NAME:$VERSION $IMAGE_NAME:latest

      - name: Run container test
        run: |
          docker run -d -p 5000:5000 --name test-container $IMAGE_NAME:$VERSION
          sleep 5
          curl -f http://localhost:5000 || exit 1
          docker rm -f test-container

      - name: Push images
        run: |
          docker push $IMAGE_NAME:$VERSION
          docker push $IMAGE_NAME:latest

      - name: Deploy to EC2 (Safe + Rollback)
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            set -e

            IMAGE_NAME=${{ env.IMAGE_NAME }}
            CONTAINER_NAME=${{ env.CONTAINER_NAME }}
            NEW_CONTAINER=${{ env.NEW_CONTAINER }}
            VERSION=${{ env.VERSION }}

            PREVIOUS_IMAGE=$(docker inspect $CONTAINER_NAME --format='{{.Config.Image}}' || true)

            docker pull $IMAGE_NAME:$VERSION

            docker run -d \
              --name $NEW_CONTAINER \
              -p 8080:5000 \
              --restart always \
              $IMAGE_NAME:$VERSION

            sleep 8

            if curl -f http://localhost:8080; then

              docker stop $CONTAINER_NAME || true
              docker rm $CONTAINER_NAME || true

              docker stop $NEW_CONTAINER
              docker rm $NEW_CONTAINER

              docker run -d \
                --name $CONTAINER_NAME \
                -p 80:5000 \
                --restart always \
                $IMAGE_NAME:$VERSION

              sleep 15

              RUNNING=$(docker inspect -f '{{.State.Running}}' $CONTAINER_NAME)

              if [ "$RUNNING" != "true" ]; then
                docker rm -f $CONTAINER_NAME || true

                if [ ! -z "$PREVIOUS_IMAGE" ]; then
                  docker run -d \
                    --name $CONTAINER_NAME \
                    -p 80:5000 \
                    --restart always \
                    $PREVIOUS_IMAGE
                fi

                exit 1
              fi

            else

              docker stop $NEW_CONTAINER || true
              docker rm $NEW_CONTAINER || true

              if [ ! -z "$PREVIOUS_IMAGE" ]; then
                docker stop $CONTAINER_NAME || true
                docker rm $CONTAINER_NAME || true

                docker run -d \
                  --name $CONTAINER_NAME \
                  -p 80:5000 \
                  --restart always \
                  $PREVIOUS_IMAGE
              fi

              exit 1
            fi

            docker ps
